window.FLASHCARD_DATA = {
  PORTS: [
    {port:"20/21",service:"FTP",note:"20=data, 21=control"},
    {port:"22",service:"SSH",note:"Secure shell"},
    {port:"23",service:"Telnet",note:"Insecure remote"},
    {port:"25",service:"SMTP",note:"Email sending"},
    {port:"53",service:"DNS",note:"Name resolution"},
    {port:"67/68",service:"DHCP",note:"Server/Client"},
    {port:"80",service:"HTTP",note:"Unencrypted web"},
    {port:"110",service:"POP3",note:"Email retrieval"},
    {port:"143",service:"IMAP",note:"Email retrieval"},
    {port:"161/162",service:"SNMP",note:"Network mgmt"},
    {port:"389",service:"LDAP",note:"Directory services"},
    {port:"443",service:"HTTPS",note:"Encrypted web"},
    {port:"445",service:"SMB/CIFS",note:"File sharing"},
    {port:"587",service:"SMTP TLS",note:"Secure email send"},
    {port:"636",service:"LDAPS",note:"Secure LDAP"},
    {port:"993",service:"IMAPS",note:"Secure IMAP"},
    {port:"995",service:"POP3S",note:"Secure POP3"},
    {port:"3389",service:"RDP",note:"Remote Desktop"},
    {port:"137-139",service:"NetBIOS",note:"Legacy file sharing"},
    {port:"548",service:"AFP",note:"Apple File Protocol"},
    {port:"427",service:"SLP",note:"Service Location"},
    {port:"5900",service:"VNC",note:"Virtual Network Computing"}
  ],
  ACRONYMS: [
    {a:"PSU",f:"Power Supply Unit"},{a:"DIMM",f:"Dual Inline Memory Module"},
    {a:"SO-DIMM",f:"Small Outline DIMM"},{a:"ECC",f:"Error-Correcting Code"},
    {a:"NVMe",f:"Non-Volatile Memory Express"},{a:"SATA",f:"Serial ATA"},
    {a:"RAID",f:"Redundant Array of Independent Disks"},{a:"POST",f:"Power-On Self-Test"},
    {a:"UEFI",f:"Unified Extensible Firmware Interface"},{a:"TPM",f:"Trusted Platform Module"},
    {a:"BIOS",f:"Basic Input/Output System"},{a:"CMOS",f:"Complementary Metal-Oxide Semiconductor"},
    {a:"UTP",f:"Unshielded Twisted Pair"},{a:"PoE",f:"Power over Ethernet"},
    {a:"VLAN",f:"Virtual Local Area Network"},{a:"DHCP",f:"Dynamic Host Configuration Protocol"},
    {a:"DNS",f:"Domain Name System"},{a:"CIDR",f:"Classless Inter-Domain Routing"},
    {a:"SLAAC",f:"Stateless Address Autoconfiguration"},{a:"APIPA",f:"Automatic Private IP Addressing"},
    {a:"SMB",f:"Server Message Block"},{a:"NFS",f:"Network File System"},
    {a:"IaaS",f:"Infrastructure as a Service"},{a:"PaaS",f:"Platform as a Service"},
    {a:"SaaS",f:"Software as a Service"},{a:"NTFS",f:"New Technology File System"},
    {a:"GPT",f:"GUID Partition Table"},{a:"MBR",f:"Master Boot Record"},
    {a:"MMC",f:"Microsoft Management Console"},{a:"DISM",f:"Deployment Image Servicing & Management"},
    {a:"SFC",f:"System File Checker"},{a:"EFS",f:"Encrypting File System"},
    {a:"MFA",f:"Multi-Factor Authentication"},{a:"AIO",f:"All-In-One (liquid cooling)"},
    {a:"ONT",f:"Optical Network Terminal"},{a:"PBQ",f:"Performance-Based Question"}
  ]
};
