window.T = {
en:{
  _name:"English",_code:"us",
  sprint:"4-DAY SPRINT",title:"A+ Study Map",
  subtitle1:"Core 1 (220-1101): 675/900 · 90 questions · 90 min",
  subtitle2:"Core 2 (220-1102): 700/900 · 90 questions · 90 min",
  topicsCovered:"topics covered",
  studyMap:"Study Map",ports:"Ports",acronyms:"Acronyms",
  tapToReveal:"Tap card to reveal",whatService:"What service / port?",
  whatStandFor:"What does it stand for?",prev:"← Prev",next:"Next →",
  quickRef:"Quick Reference",secPlus:"Security+ Study Tool",resetAll:"Reset All Progress",
  resetConfirm:"Reset all progress? This can't be undone.",
  confidence:"Confidence:",
  conf1:"🔴 Not yet",conf2:"🟡 Shaky",conf3:"🟢 Solid",conf4:"💎 Locked",
  openLab:"Open in TestOut",
  core1:"CORE 1",core2:"CORE 2",
  day1:"HARDWARE & POWER",day1sub:"Core 1 — PSUs, Storage, Memory, CPUs, Boot & Failures",
  day2:"NETWORKING & CLOUD",day2sub:"Core 1 — Cabling, IP, Services, Cloud, Mobile, Printers",
  day3:"OPERATING SYSTEMS",day3sub:"Core 2 — Windows, Linux, macOS, Tools & Support",
  day4:"SECURITY & OPS",day4sub:"Core 2 — Threats, Protection, Operations, AI & Practice Exams",
  day1short:"HARDWARE",day2short:"NETWORKING",day3short:"OS",day4short:"SECURITY",
  /* Block titles */
  b1:"Power Supply & Cooling",b2:"Storage Devices & RAID",b3:"Memory & CPU Architecture",
  b4:"BIOS/UEFI & Boot Troubleshooting",b5:"System Failures & Overheating",
  b6:"Networking Hardware & Cabling",b7:"IP Addressing & Network Services",
  b8:"Cloud, Mobile & Printing",
  b9:"Windows OS Fundamentals",b10:"Windows Tools & Settings",
  b11:"OS Support & Recovery",b12:"Linux & macOS",
  b13:"Account Security & Threats",b14:"Protection & Defenses",
  b15:"Operations, Scripting & AI",b16:"Practice Exams & Exam Strategy",
  /* Topics */
  t1:"Power Supply Units (PSU) — form factors, modular vs fixed",
  t2:"Wattage Rating — calculating power requirements",
  t3:"Power Supply Connectors — 24-pin, 8-pin CPU, PCIe, SATA, Molex",
  t4:"Fan Cooling Systems — case fans, CPU coolers, airflow direction",
  t5:"Liquid Cooling Systems — AIO vs custom loop, radiators, pumps",
  t6:"Storage Devices — types overview, interfaces (SATA, NVMe, M.2)",
  t7:"Solid State Drives (SSDs) — NAND types, form factors, wear leveling",
  t8:"Hard Disk Drives (HDDs) — platters, RPM, cache, seek time",
  t9:"RAID — levels 0, 1, 5, 6, 10 — striping, mirroring, parity",
  t10:"Optical Drives — CD, DVD, Blu-ray, read/write speeds",
  t11:"System RAM — DDR4, DDR5, DIMM vs SO-DIMM, speeds & latency",
  t12:"ECC RAM — error-correcting code, server vs workstation use",
  t13:"CPU Architecture — x86 vs ARM, cores, threads, cache levels",
  t14:"CPU Sockets — Intel (LGA) vs AMD (PGA/LGA), compatibility",
  t15:"BIOS/UEFI — POST, boot order, Secure Boot, firmware updates",
  t16:"TPM (Trusted Platform Module) — hardware security, key storage",
  t17:"Troubleshoot POST — beep codes, diagnostic LEDs, no-display fixes",
  t18:"Power Issues — no power, intermittent shutdown, PSU testing",
  t19:"RAID Failure — degraded arrays, rebuild procedures, hot spares",
  t20:"Overheating — thermal paste, heatsink mounting, throttling signs",
  t21:"Switches — managed vs unmanaged, VLANs, PoE",
  t22:"UTP Cabling — Cat 5e/6/6a, T568A/B, crimping, cable testing",
  t23:"Modems — DSL, Cable, Fiber ONT, gateway devices",
  t24:"IPv4 Addressing — classes, subnetting, CIDR, private ranges",
  t25:"IPv6 Addressing — notation, link-local, global unicast, SLAAC",
  t26:"DHCP — leases, scopes, reservations, relay agents",
  t27:"DNS — records (A, AAAA, MX, CNAME, PTR), resolution process",
  t28:"File/Print Servers — SMB/CIFS, NFS, shared permissions",
  t29:"Proxy Servers — forward vs reverse proxy, content filtering",
  t30:"IoT Devices — smart devices, Zigbee, Z-Wave, security concerns",
  t31:"Hypervisors — Type 1 vs Type 2, VM snapshots, resource allocation",
  t32:"Cloud Characteristics — IaaS, PaaS, SaaS, public/private/hybrid",
  t33:"Mobile Hotspots — tethering, data limits, security",
  t34:"Battery Replacement — Li-ion safety, calibration, swelling risks",
  t35:"Laser Printer Process — 7 steps: Processing through Cleaning",
  t36:"Print Quality Issues — ghosting, streaks, smearing, paper jams",
  t37:"Windows / macOS — edition comparison, feature differences",
  t38:"Windows File Systems — NTFS, FAT32, exFAT, permissions model",
  t39:"Control Panel — applets, system settings, legacy vs Settings app",
  t40:"Administrative Tools — MMC snap-ins, Computer Management, Services",
  t41:"Disk Management — partitions (MBR vs GPT), volumes, format types",
  t42:"Command Prompt — dir, cd, ipconfig, sfc, chkdsk, DISM, net commands",
  t43:"Event Viewer — log types (System, Application, Security), filtering",
  t44:"Task Manager — processes, performance, startup, services tabs",
  t45:"System Restore — restore points, snapshot behavior, limitations",
  t46:"Linux Navigation — ls, cd, pwd, grep, chmod, sudo, package managers",
  t47:"Time Machine (macOS) — backup config, restore procedures, APFS snapshots",
  t48:"Logical Security — user accounts, groups, NTFS vs share permissions",
  t49:"Password Best Practices — complexity, length, MFA, password managers",
  t50:"Social Engineering — phishing, vishing, tailgating, pretexting",
  t51:"Malware Vectors — email, USB, drive-by downloads, supply chain",
  t52:"Defender Antivirus — real-time protection, scans, exclusions",
  t53:"BitLocker — full-disk encryption, TPM requirement, recovery keys",
  t54:"Backups — full, incremental, differential, 3-2-1 rule",
  t55:"Change Requests — documentation, rollback plans, approval process",
  t56:"Shell Scripts — batch files, PowerShell, bash basics, automation",
  t57:"AI Application Integration — copilots, prompt engineering basics",
  t58:"Private vs Public AI — data privacy, model hosting, enterprise concerns",
  t59:"Core 1 Exam Details — domain weights, question types, PBQ strategy",
  t60:"Core 2 Exam Details — domain weights, passing score differences",
  t61:"Exam Tips — time management, PBQ skip strategy, elimination method",
  t62:"Full timed practice exam — simulate test day conditions",
  /* Tips */
  tip1:"The 7 laser printer steps are GUARANTEED on the exam. Memorize the order.",
  tip2:"Know RAID levels cold: 0 = speed no redundancy, 1 = mirror, 5 = parity (min 3), 10 = mirror + stripe.",
  tip3:"DDR generations don't mix — DDR4 won't fit DDR5 slots. Know notch positions and voltage differences.",
  tip4:"1 short beep = POST success, continuous/repeating beeps usually mean memory issues.",
  tip5:"Troubleshoot order: wall outlet → power cable → PSU switch → PSU test → motherboard.",
  tip6:"T568B is the standard for straight-through. Know both A and B pinouts.",
  tip7:"Private IPs: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16. APIPA: 169.254.x.x = DHCP failure.",
  tip8:"Cloud characteristics: IaaS, PaaS, SaaS, public/private/hybrid.",
  tip9:"NTFS supports permissions, EFS encryption, compression, large files. FAT32 has 4GB file limit.",
  tip10:"sfc /scannow fixes system files, DISM repairs the image, chkdsk fixes disk errors. Order matters.",
  tip11:"Event Viewer levels: Information → Warning → Error → Critical. Security logs need auditing enabled.",
  tip12:"Linux permissions: rwx=7, rw-=6, r-x=5, r--=4. chmod 755 = owner full, group/others read+execute.",
  tip13:"MFA factors: something you know/have/are. Two of the SAME type is NOT MFA.",
  tip14:"BitLocker requires TPM 1.2+. Without TPM, you need a USB startup key.",
  tip15:"3-2-1 backup: 3 copies, 2 media types, 1 offsite. Know incremental vs differential.",
  tip16:"Core 1 = 675/900 (≈75%). Core 2 = 700/900 (≈78%). Skip PBQs first pass.",
  /* Guides */
  g1:"Module 3.1",g2:"Module 3.2",g3:"Module 3.3-3.4",g4:"Module 4.1",g5:"Module 4.2-4.3",
  g6:"Module 5.2-6.1",g7:"Module 6.2-6.4",g8:"Module 7.1-10.3",g9:"Module 11.3",g10:"Module 12.1-13.2",
  g11:"Module 14.3-14.4",g12:"Module 17.1-17.3",g13:"Module 15.1-19.4",g14:"Module 19.2",g15:"Module 21.1-21.3",g16:"Appendix B-C",
  /* Time slots */
  morning:"MORNING",midday:"MIDDAY",afternoon:"AFTERNOON",evening:"EVENING",lateEvening:"LATE EVENING",
  time1:"9:00 AM – 11:00 AM",time2:"11:30 AM – 1:30 PM",time3:"2:30 PM – 4:30 PM",time4:"5:00 PM – 7:00 PM",time5:"7:30 PM – 9:00 PM",
  attribution:"Study content structured from TestOut LabSim A+ courseware modules. CompTIA A+ is a trademark of CompTIA.",
},
es:{
  _name:"Español",_code:"es",
  sprint:"SPRINT DE 4 DÍAS",title:"Mapa de Estudio A+",
  subtitle1:"Core 1 (220-1101): 675/900 · 90 preguntas · 90 min",
  subtitle2:"Core 2 (220-1102): 700/900 · 90 preguntas · 90 min",
  topicsCovered:"temas cubiertos",
  studyMap:"Mapa de Estudio",ports:"Puertos",acronyms:"Acrónimos",
  tapToReveal:"Toca la tarjeta para revelar",whatService:"¿Qué servicio / puerto?",
  whatStandFor:"¿Qué significa?",prev:"← Anterior",next:"Siguiente →",
  quickRef:"Referencia Rápida",secPlus:"Herramienta de Estudio Security+",resetAll:"Reiniciar Todo",
  resetConfirm:"¿Reiniciar todo el progreso? No se puede deshacer.",
  confidence:"Confianza:",
  conf1:"🔴 Aún no",conf2:"🟡 Inestable",conf3:"🟢 Sólido",conf4:"💎 Dominado",
  openLab:"Abrir en TestOut",
  core1:"CORE 1",core2:"CORE 2",
  day1:"HARDWARE Y ENERGÍA",day1sub:"Core 1 — Fuentes, Almacenamiento, Memoria, CPUs, Arranque y Fallos",
  day2:"REDES Y NUBE",day2sub:"Core 1 — Cableado, IP, Servicios, Nube, Móvil, Impresoras",
  day3:"SISTEMAS OPERATIVOS",day3sub:"Core 2 — Windows, Linux, macOS, Herramientas y Soporte",
  day4:"SEGURIDAD Y OPERACIONES",day4sub:"Core 2 — Amenazas, Protección, Operaciones, IA y Exámenes",
  day1short:"HARDWARE",day2short:"REDES",day3short:"SO",day4short:"SEGURIDAD",
  /* Block titles */
  b1:"Fuente de Poder y Enfriamiento",b2:"Almacenamiento y RAID",b3:"Memoria y CPU",
  b4:"BIOS/UEFI y Arranque",b5:"Fallos y Sobrecalentamiento",
  b6:"Hardware de Red",b7:"IP y Servicios",b8:"Nube y Móvil",
  b9:"Fundamentos de Windows",b10:"Herramientas de Windows",
  b11:"Soporte y Recuperación",b12:"Linux y macOS",
  b13:"Amenazas y Cuentas",b14:"Protección",
  b15:"Operaciones e IA",b16:"Estrategia de Examen",
  /* Topics */
  t1:"Fuentes de poder (PSU) — factores de forma, modular vs fija",
  t2:"Clasificación de vatios — cálculo de requisitos",
  t3:"Conectores de fuente — 24-pin, 8-pin CPU, PCIe, SATA, Molex",
  t4:"Ventilación — ventiladores, disipadores, flujo de aire",
  t5:"Enfriamiento líquido — AIO vs personalizado",
  t6:"Almacenamiento — tipos, interfaces (SATA, NVMe, M.2)",
  t7:"Unidades SSD — tipos NAND, factores de forma",
  t8:"Discos duros (HDD) — RPM, caché, tiempo de búsqueda",
  t9:"RAID — niveles 0, 1, 5, 6, 10 — espejo, paridad",
  t10:"Unidades ópticas — CD, DVD, Blu-ray",
  t11:"RAM del sistema — DDR4, DDR5, DIMM vs SO-DIMM",
  t12:"RAM ECC — corrección de errores, servidores",
  t13:"Arquitectura CPU — x86 vs ARM, núcleos, hilos",
  t14:"Sockets CPU — Intel (LGA) vs AMD (PGA/LGA)",
  t15:"BIOS/UEFI — POST, orden de arranque, Secure Boot",
  t16:"TPM — seguridad de hardware, claves",
  t17:"Resolución POST — códigos de pitido, LEDs",
  t18:"Problemas de energía — sin energía, apagado inesperado",
  t19:"Fallo de RAID — reconstrucción, hot spares",
  t20:"Sobrecalentamiento — pasta térmica, throttling",
  t21:"Switches — gestionados, VLANs, PoE",
  t22:"Cableado UTP — Cat 5e/6/6a, T568A/B, crimpado",
  t23:"Módems — DSL, Cable, Fibra ONT",
  t24:"IPv4 — clases, subredes, CIDR, rangos privados",
  t25:"IPv6 — notación, link-local, SLAAC",
  t26:"DHCP — arrendamientos, ámbitos, reservas",
  t27:"DNS — registros (A, MX, CNAME), resolución",
  t28:"Servidores — SMB/CIFS, NFS, permisos",
  t29:"Proxy — directo vs inverso, filtrado",
  t30:"IoT — Zigbee, Z-Wave, seguridad",
  t31:"Hipervisores — Tipo 1 vs Tipo 2, snapshots",
  t32:"Nube — IaaS, PaaS, SaaS, pública/privada",
  t33:"Hotspots móviles — tethering, seguridad",
  t34:"Baterías — seguridad Li-ion, hinchazón",
  t35:"Impresora láser — 7 pasos: Procesamiento a Limpieza",
  t36:"Calidad de impresión — fantasmas, manchas, atascos",
  t37:"Windows / macOS — comparación de ediciones",
  t38:"Sistemas de archivos — NTFS, FAT32, exFAT",
  t39:"Panel de Control — applets, configuración",
  t40:"Herramientas — MMC, Administración de equipos, Servicios",
  t41:"Discos — particiones (MBR vs GPT), volúmenes",
  t42:"Línea de comandos — ipconfig, sfc, chkdsk, DISM, net",
  t43:"Visor de eventos — Sistema, Aplicación, Seguridad",
  t44:"Administrador de tareas — procesos, rendimiento",
  t45:"Restaurar sistema — puntos de restauración",
  t46:"Linux — ls, cd, pwd, grep, chmod, sudo",
  t47:"Time Machine — respaldos, restauración",
  t48:"Seguridad lógica — cuentas, grupos, permisos",
  t49:"Contraseñas — complejidad, MFA, gestores",
  t50:"Ingeniería social — phishing, vishing, tailgating",
  t51:"Malware — vectores, USB, cadena de suministro",
  t52:"Antivirus Defender — tiempo real, escaneos",
  t53:"BitLocker — cifrado, requisito TPM",
  t54:"Respaldos — total, incremental, diferencial, 3-2-1",
  t55:"Cambios — documentación, reversión, aprobación",
  t56:"Scripts — archivos batch, PowerShell, bash",
  t57:"IA — copilotos, ingeniería de prompts",
  t58:"IA privada vs pública — privacidad de datos",
  t59:"Examen Core 1 — pesos, PBQs, estrategia",
  t60:"Examen Core 2 — pesos, diferencias de puntaje",
  t61:"Consejos — gestión de tiempo, eliminación",
  t62:"Examen de práctica — simulación real",
  /* Tips */
  tip1:"Los 7 pasos de la impresora láser son GARANTIZADOS. Memoriza el orden.",
  tip2:"RAID: 0 = velocidad, 1 = espejo, 5 = paridad (mín 3), 10 = espejo + stripe.",
  tip3:"DDR no se mezcla. DDR4 no entra en slots DDR5.",
  tip4:"1 pitido corto = éxito. Pitidos continuos suelen ser memoria.",
  tip5:"Orden: enchufe → cable → interruptor PSU → prueba PSU → placa.",
  tip6:"T568B es el estándar. Conoce los esquemas A y B.",
  tip7:"IPs privadas: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16. APIPA: 169.254.x.x.",
  tip8:"Modelos nube: IaaS, PaaS, SaaS.",
  tip9:"NTFS soporta permisos y cifrado. FAT32 límite 4GB.",
  tip10:"sfc /scannow repara archivos, DISM repara imagen.",
  tip11:"Visor eventos: Información → Advertencia → Error → Crítico.",
  tip12:"Linux: rwx=7, rw-=6, r-x=5, r--=4. chmod 755.",
  tip13:"MFA: algo que sabes/tienes/eres. Dos del MISMO tipo NO es MFA.",
  tip14:"BitLocker necesita TPM 1.2+. Sin TPM usa llave USB.",
  tip15:"3-2-1: 3 copias, 2 medios, 1 fuera de sitio.",
  tip16:"Core 1 = 675/900. Core 2 = 700/900. Salta PBQs al inicio.",
  /* Guides */
  g1:"Módulo 3.1",g2:"Módulo 3.2",g3:"Módulo 3.3-3.4",g4:"Módulo 4.1",g5:"Módulo 4.2-4.3",
  g6:"Módulo 5.2-6.1",g7:"Módulo 6.2-6.4",g8:"Módulo 7.1-10.3",g9:"Módulo 11.3",g10:"Módulo 12.1-13.2",
  g11:"Módulo 14.3-14.4",g12:"Módulo 17.1-17.3",g13:"Módulo 15.1-19.4",g14:"Módulo 19.2",g15:"Módulo 21.1-21.3",g16:"Apéndice B-C",
  morning:"MAÑANA",midday:"MEDIODÍA",afternoon:"TARDE",evening:"NOCHE",lateEvening:"NOCHE TARDE",
  time1:"9:00 AM – 11:00 AM",time2:"11:30 AM – 1:30 PM",time3:"2:30 PM – 4:30 PM",time4:"5:00 PM – 7:00 PM",time5:"7:30 PM – 9:00 PM",
  attribution:"Contenido estructurado a partir de los módulos de TestOut LabSim A+. CompTIA A+ es marca registrada de CompTIA.",
},
fr:{
  _name:"Français",_code:"fr",
  sprint:"SPRINT DE 4 JOURS",title:"Plan d'Étude A+",
  studyMap:"Plan d'Étude",ports:"Ports",acronyms:"Acronymes",secPlus:"Outil d'Étude Security+",
  tapToReveal:"Appuyez pour révéler",prev:"← Préc",next:"Suiv →",
  attribution:"Contenu structuré à partir des modules TestOut LabSim A+. CompTIA A+ est une marque de CompTIA.",
},
de:{
  _name:"Deutsch",_code:"de",
  sprint:"4-TAGE-SPRINT",title:"A+ Lernplan",
  studyMap:"Lernplan",ports:"Ports",acronyms:"Akronyme",secPlus:"Security+ Lern-Tool",
  tapToReveal:"Tippen zum Enthüllen",prev:"← Zurück",next:"Weiter →",
  attribution:"Inhalte basierend auf TestOut LabSim A+. CompTIA A+ ist eine Marke von CompTIA.",
},
pt:{
  _name:"Português",_code:"br",
  sprint:"SPRINT DE 4 DIAS",title:"Mapa de Estudo A+",
  studyMap:"Mapa de Estudo",ports:"Portas",acronyms:"Acrônimos",secPlus:"Ferramenta de Estudo Security+",
  tapToReveal:"Toque para revelar",prev:"← Ant",next:"Próx →",
  attribution:"Conteúdo estruturado a partir dos módulos TestOut LabSim A+. CompTIA A+ é uma marca da CompTIA.",
},
it:{
  _name:"Italiano",_code:"it",
  sprint:"SPRINT DI 4 GIORNI",title:"Mappa di Studio A+",
  studyMap:"Mappa di Studio",ports:"Porte",acronyms:"Acronimi",secPlus:"Strumento di Studio Security+",
  tapToReveal:"Tocca per rivelare",prev:"← Prec",next:"Succ →",
  attribution:"Contenuto strutturato dai moduli TestOut LabSim A+. CompTIA A+ è un marchio di CompTIA.",
},
nl:{
  _name:"Nederlands",_code:"nl",
  sprint:"4-DAAGSE SPRINT",title:"A+ Studiekaart",
  studyMap:"Studiekaart",ports:"Poorten",acronyms:"Acroniemen",secPlus:"Security+ Studietool",
  tapToReveal:"Tik om te onthullen",prev:"← Vorige",next:"Volgende →",
  attribution:"Inhoud gestructureerd op basis van TestOut LabSim A+. CompTIA A+ is een handelsmerk van CompTIA.",
},
ru:{
  _name:"Русский",_code:"ru",
  sprint:"4-ДНЕВНЫЙ СПРИНТ",title:"План обучения A+",
  studyMap:"План обучения",ports:"Порты",acronyms:"Акронимы",secPlus:"Инструмент для обучения Security+",
  tapToReveal:"Нажмите, чтобы открыть",prev:"← Назад",next:"Вперед →",
  attribution:"Контент структурирован на основе модулей TestOut LabSim A+. CompTIA A+ является торговой маркой CompTIA.",
},
zh:{
  _name:"简体中文",_code:"cn",
  sprint:"4天冲刺",title:"A+ 学习地图",
  studyMap:"学习地图",ports:"端口",acronyms:"缩写",secPlus:"Security+ 学习工具",
  tapToReveal:"点击揭晓",prev:"← 上一项",next:"下一项 →",
  attribution:"内容根据 TestOut LabSim A+ 课程模块构建。CompTIA A+ 是 CompTIA 的商标。",
},
ja:{
  _name:"日本語",_code:"jp",
  sprint:"4日間スプリント",title:"A+ 学習マップ",
  studyMap:"学習マップ",ports:"ポート",acronyms:"略語",secPlus:"Security+ 学習ツール",
  tapToReveal:"タップで表示",prev:"← 前へ",next:"次へ →",
  attribution:"TestOut LabSim A+ モジュールに基づいて構成。CompTIA A+ は CompTIA の商標です。",
},
ko:{
  _name:"한국어",_code:"kr",
  sprint:"4일 집중 과정",title:"A+ 학습 지도",
  studyMap:"학습 지도",ports:"포트",acronyms:"약어",secPlus:"Security+ 학습 도구",
  tapToReveal:"탭하여 확인",prev:"← 이전",next:"다음 →",
  attribution:"TestOut LabSim A+ 모듈을 기반으로 구성됨. CompTIA A+는 CompTIA의 상표입니다.",
},
hi:{
  _name:"हिन्दी",_code:"in",
  sprint:"4-दिवसीय स्प्रिंट",title:"A+ अध्ययन मानचित्र",
  studyMap:"अध्ययन मानचित्र",ports:"पोर्ट",acronyms:"संक्षिप्तीकरण",secPlus:"Security+ अध्ययन उपकरण",
  tapToReveal:"दिखाने के लिए टैप करें",prev:"← पिछला",next:"अगला →",
  attribution:"TestOut LabSim A+ मॉड्यूल से संरचित। CompTIA A+, CompTIA का ट्रेडमार्क है।",
},
ar:{
  _name:"العربية",_code:"sa",
  sprint:"سبرينت 4 أيام",title:"خريطة دراسة A+",
  studyMap:"خريطة الدراسة",ports:"المنافذ",acronyms:"الاختصارات",secPlus:"أداة دراسة Security+",
  tapToReveal:"اضغط للكشف",prev:"← السابق",next:"التالي →",
  attribution:"المحتوى منظم من وحدات TestOut LabSim A+. CompTIA A+ هي علامة تجارية لشركة CompTIA.",
},
af:{
  _name:"Afrikaans",
  _code:"za",
  sprint:"4-DAE SPRINT",
  title:"A+ Studiekaart",
  subtitle1:"Core 1 (220-1101): 675/900 · 90 vrae · 90 min",
  subtitle2:"Core 2 (220-1102): 700/900 · 90 vrae · 90 min",
  topicsCovered:"onderwerpe gedek",
  studyMap:"Studiekaart",
  ports:"Poorte",
  acronyms:"Akronieme",
  tapToReveal:"Tik kaart om te onthul",
  whatService:"Watter diens / poort?",
  whatStandFor:"Waarvoor staan dit?",
  prev:"← Vorige",
  next:"Volgende →",
  quickRef:"Vinnige Verwysing",
  secPlus:"Security+ Studie-instrument",
  resetAll:"Stel Alle Vorderings Terug",
  resetConfirm:"Stel alle vordering terug? Dit kan nie ongedaan gemaak word nie.",
  confidence:"Selfvertroue:",
  conf1:"🔴 Nog nie",
  conf2:"🟡 Onvas",
  conf3:"🟢 Solid",
  conf4:"💎 Gesluit",
  openLab:"Maak oop in TestOut",
  core1:"CORE 1",
  core2:"CORE 2",
  day1:"HARDWARE & KRAG",
  day1sub:"Core 1 — PSU's, Berging, Geheue, CPU's, Selflaai & Foute",
  day2:"NETWERKE & WOLK",
  day2sub:"Core 1 — Kabels, IP, Dienste, Wolk, Mobiel, Drukkers",
  day3:"BEDRYFSTELSELS",
  day3sub:"Core 2 — Windows, Linux, macOS, Gereedskap & Ondersteuning",
  day4:"SEKURITEIT & OPS",
  day4sub:"Core 2 — Bedreigings, Beskerming, Bedrywighede, KI & Oefeneksamens",
  day1short:"HARDWARE",
  day2short:"NETWERKE",
  day3short:"OS",
  day4short:"SEKURITEIT",
  b1:"Kragtoevoer & Verkoeling",
  b2:"Bergingstoestelle & RAID",
  b3:"Geheue & CPU Argitektuur",
  b4:"BIOS/UEFI & Selflaai Foutsporing",
  b5:"Stelselfoute & Oorverhitting",
  b6:"Netwerkhardeware & Kabels",
  b7:"IP-adressering & Netwerkdienste",
  b8:"Wolk, Mobiel & Drukwerk",
  b9:"Windows OS Grondbeginsels",
  b10:"Windows Gereedskap & Instellings",
  b11:"OS Ondersteuning & Herstel",
  b12:"Linux & macOS",
  b13:"Rekeningsekuriteit & Bedreigings",
  b14:"Beskerming & Verdediging",
  b15:"Bedrywighede, Scripting & KI",
  b16:"Oefeneksamens & Eksamenstrategie",
  t1:"Kragtoevoereenhede (PSU) — vormfaktore, modulêr vs vas",
  t2:"Watt-gradering — berekening van kragvereistes",
  t3:"Kragtoevoer-verbindings — 24-pen, 8-pen CPU, PCIe, SATA, Molex",
  t4:"Waaierverkoelingstelsels — kaswaaiers, CPU-verkoelers, lugvloeirigting",
  t5:"Vloeistofverkoelingstelsels — AIO vs pasgemaakte lus, verkoelers, pompe",
  t6:"Bergingstoestelle — tipes oorsig, koppelvlakke (SATA, NVMe, M.2)",
  t7:"Solid State Drives (SSD's) — NAND-tipes, vormfaktore, slytasienivellering",
  t8:"Hardeskyf-aandrywers (HDD's) — plate, RPM, kas, soektyd",
  t9:"RAID — vlakke 0, 1, 5, 6, 10 — stroop, spieël, pariteit",
  t10:"Optiese aandrywers — CD, DVD, Blu-ray, lees/skryfspoed",
  t11:"Stelsel RAM — DDR4, DDR5, DIMM vs SO-DIMM, spoed & vertraging",
  t12:"ECC RAM — foutkorrigerende kode, bediener vs werkstasie gebruik",
  t13:"CPU Argitektuur — x86 vs ARM, kerne, drade, kasvlakke",
  t14:"CPU-sokke — Intel (LGA) vs AMD (PGA/LGA), versoenbaarheid",
  t15:"BIOS/UEFI — POST, selflaai-volgorde, Secure Boot, firmware-opdaterings",
  t16:"TPM (Trusted Platform Module) — hardeware-sekuriteit, sleutelberging",
  t17:"Foutspoor POST — piepkodes, diagnostiese LED's, geen-vertoon regstellings",
  t18:"Kragprobleme — geen krag, onderbroke afskakeling, PSU-toetsing",
  t19:"RAID-fout — gedegradeerde skikkings, herbouprosedures, warm spaarwiele",
  t20:"Oorverhitting — termiese pasta, heatsink-montering, tekens van smoor",
  t21:"Skakelaars — bestuur vs onbeheerd, VLAN's, PoE",
  t22:"UTP-kabels — Cat 5e/6/6a, T568A/B, krimp, kabeltoetsing",
  t23:"Modems — DSL, Kabel, Vesel ONT, poorttoestelle",
  t24:"IPv4-adressering — klasse, subnetting, CIDR, privaat reekse",
  t25:"IPv6-adressering — notasie, skakel-plaaslik, globale unikis, SLAAC",
  t26:"DHCP — hure, omvang, besprekings, aflosagente",
  t27:"DNS — rekords (A, AAAA, MX, CNAME, PTR), resolusieproses",
  t28:"Lêer/Drukbedieners — SMB/CIFS, NFS, gedeelde toestemmings",
  t29:"Instaanbedieners — vorentoe vs omgekeerde instaanbediener, inhoudfiltrering",
  t30:"IoT-toestelle — slim toestelle, Zigbee, Z-Wave, sekuriteitsbekommernisse",
  t31:"Hipervisors — Tipe 1 vs Tipe 2, VM-kiekies, hulpbron-toekenning",
  t32:"Wolk-eienskappe — IaaS, PaaS, SaaS, publiek/privaat/hibried",
  t33:"Mobiele Hotspots — verbinding, datalimiete, sekuriteit",
  t34:"Batteryvervanging — Li-ion veiligheid, kalibrasie, swellingrisiko's",
  t35:"Laser-drukproses — 7 stappe: Verwerking tot Skoonmaak",
  t36:"Drukkwaliteit-kwessies — spoke, strepe, smeer, papieropeenhopings",
  t37:"Windows / macOS — uitgawevergelyking, kenmerkverskille",
  t38:"Windows Lêerstelsels — NTFS, FAT32, exFAT, toestemmingsmodel",
  t39:"Beheerpaneel — applets, stelselinstellings, erfenis vs Instellings-app",
  t40:"Administratiewe Gereedskap — MMC-invoegtoepassings, Rekenaarbestuur, Dienste",
  t41:"Skyfbestuur — partisies (MBR vs GPT), volumes, formaattipes",
  t42:"Opdragprompt — dir, cd, ipconfig, sfc, chkdsk, DISM, net-opdragte",
  t43:"Gebeurteniskyker — log-tipes (Stelsel, Toepassing, Sekuriteit), filtrering",
  t44:"Taakbestuurder — prosesse, prestasie, selflaai, dienste-oortjies",
  t45:"Stelselherstel — herstelpunte, kiekie-gedrag, beperkings",
  t46:"Linux-navigasie — ls, cd, pwd, grep, chmod, sudo, pakketbestuurders",
  t47:"Time Machine (macOS) — rugsteun-konfigurasie, herstelprosedures, APFS-kiekies",
  t48:"Logiese Sekuriteit — gebruikersrekeninge, groepe, NTFS vs gedeelde toestemmings",
  t49:"Wagwoord Beste Praktyke — kompleksiteit, lengte, MFA, wagwoordbestuurders",
  t50:"Sosiale Ingenieurswese — uitvissing, vishing, tailgating, pretexting",
  t51:"Malware-vektore — e-pos, USB, ry-by-aflaai, voorsieningsketting",
  t52:"Defender Antivirus — intydse beskerming, skanderings, uitsluitings",
  t53:"BitLocker — volle-skyf-enkripsie, TPM-vereiste, herstelsleutels",
  t54:"Rugsteun — volledig, inkrementeel, differensieel, 3-2-1 reël",
  t55:"Veranderingsversoeke — dokumentasie, terugrolplanne, goedkeuringsproses",
  t56:"Shell Scripts — bondellêers, PowerShell, bash-basiese beginsels, outomatisering",
  t57:"KI-toepassingsintegrasie — medevlieëniers, prompt-ingenieurswese basiese beginsels",
  t58:"Privaat vs Publieke KI — dataprivaatheid, modelgasheer, ondernemingsbekommernisse",
  t59:"Core 1 Eksamengegewens — domeingewigte, vraagtipes, PBQ-strategie",
  t60:"Core 2 Eksamengegewens — domeingewigte, slaagsyferverskille",
  t61:"Eksamenwenke — tydsbestuur, PBQ-oorslaanstrategie, eliminasie-metode",
  t62:"Volledige tyd-oefeneksamen — simuleer toetsdagtoestande",
  tip1:"Die 7 laser-drukkerstappe word GEWAARBORG op die eksamen. Memoriseer die volgorde.",
  tip2:"Ken RAID-vlakke goed: 0 = spoed geen redundansie, 1 = spieël, 5 = pariteit (min 3), 10 = spieël + stroop.",
  tip3:"DDR-generasies meng nie — DDR4 sal nie in DDR5-gleuwe pas nie. Ken kerfposisies en spanningsverskille.",
  tip4:"1 kort piep = POST sukses, aanhoudende/herhaalde piep beteken gewoonlik geheueprobleme.",
  tip5:"Foutspoor-volgorde: muuraansluiting → kragkabel → PSU-skakelaar → PSU-toets → moederbord.",
  tip6:"T568B is die standaard vir reguit-deur. Ken beide A en B pen-uitset.",
  tip7:"Privaat IP's: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16. APIPA: 169.254.x.x = DHCP-fout.",
  tip8:"Wolk-eienskappe: IaaS, PaaS, SaaS, publiek/privaat/hibried.",
  tip9:"NTFS ondersteun toestemmings, EFS-enkripsie, kompressie, groot lêers. FAT32 het 4GB lêerbeperking.",
  tip10:"sfc /scannow maak stelsellêers reg, DISM herstel die beeld, chkdsk maak skyffoute reg. Volgorde maak saak.",
  tip11:"Gebeurteniskyker vlakke: Inligting → Waarskuwing → Fout → Kritiek. Sekuriteitslogs benodig ouditering geaktiveer.",
  tip12:"Linux-toestemmings: rwx=7, rw-=6, r-x=5, r--=4. chmod 755 = eienaar vol, groep/ander lees+uitvoer.",
  tip13:"MFA-faktore: iets wat jy weet/het/is. Twee van dieselfde tipe is NIE MFA nie.",
  tip14:"BitLocker benodig TPM 1.2+. Sonder TPM het jy 'n USB-selflaaisleutel nodig.",
  tip15:"3-2-1 rugsteun: 3 kopieë, 2 media-tipes, 1 van die terrein af. Ken inkrementeel vs differensieel.",
  tip16:"Core 1 = 675/900 (≈75%). Core 2 = 700/900 (≈78%). Slaan PBQ's oor met die eerste rondte.",
  g1:"Module 3.1",
  g2:"Module 3.2",
  g3:"Module 3.3-3.4",
  g4:"Module 4.1",
  g5:"Module 4.2-4.3",
  g6:"Module 5.2-6.1",
  g7:"Module 6.2-6.4",
  g8:"Module 7.1-10.3",
  g9:"Module 11.3",
  g10:"Module 12.1-13.2",
  g11:"Module 14.3-14.4",
  g12:"Module 17.1-17.3",
  g13:"Module 15.1-19.4",
  g14:"Module 19.2",
  g15:"Module 21.1-21.3",
  g16:"Bylaag B-C",
  morning:"OGEND",
  midday:"MIDDAG",
  afternoon:"NAMIDDAG",
  evening:"AAND",
  lateEvening:"LAATAAND",
  time1:"9:00 VM – 11:00 VM",
  time2:"11:30 VM – 1:30 NM",
  time3:"2:30 NM – 4:30 NM",
  time4:"5:00 NM – 7:00 NM",
  time5:"7:30 NM – 9:00 NM",
  attribution:"Studie-inhoud gestruktureer vanaf TestOut LabSim A+-kursusmateriaalmodules. CompTIA A+ is 'n handelsmerk van CompTIA.",
},
};
