window.T = {
en:{
  _name:"English",_code:"us",
  sprint:"4-DAY SPRINT",title:"A+ Study Map",
  subtitle1:"Core 1 (220-1101): 675/900 · 90 questions · 90 min",
  subtitle2:"Core 2 (220-1102): 700/900 · 90 questions · 90 min",
  topicsCovered:"topics covered",
  studyMap:"Study Map",ports:"Ports",acronyms:"Acronyms",
  tapToReveal:"Tap card to reveal",whatService:"What service / port?",
  whatStandFor:"What does it stand for?",prev:"← Prev",next:"Next →",
  quickRef:"Quick Reference",resetAll:"Reset All Progress",
  resetConfirm:"Reset all progress? This can't be undone.",
  confidence:"Confidence:",
  conf1:"🔴 Not yet",conf2:"🟡 Shaky",conf3:"🟢 Solid",conf4:"💎 Locked",
  openLab:"Open in TestOut",
  core1:"CORE 1",core2:"CORE 2",
  day1:"HARDWARE & POWER",day1sub:"Core 1 — PSUs, Storage, Memory, CPUs, Boot & Failures",
  day2:"NETWORKING & CLOUD",day2sub:"Core 1 — Cabling, IP, Services, Cloud, Mobile, Printers",
  day3:"OPERATING SYSTEMS",day3sub:"Core 2 — Windows, Linux, macOS, Tools & Support",
  day4:"SECURITY & OPS",day4sub:"Core 2 — Threats, Protection, Operations, AI & Practice Exams",
  day1short:"HARDWARE",day2short:"NETWORKING",day3short:"OS",day4short:"SECURITY",
  /* Block titles */
  b1:"Power Supply & Cooling",b2:"Storage Devices & RAID",b3:"Memory & CPU Architecture",
  b4:"BIOS/UEFI & Boot Troubleshooting",b5:"System Failures & Overheating",
  b6:"Networking Hardware & Cabling",b7:"IP Addressing & Network Services",
  b8:"Cloud, Mobile & Printing",
  b9:"Windows OS Fundamentals",b10:"Windows Tools & Settings",
  b11:"OS Support & Recovery",b12:"Linux & macOS",
  b13:"Account Security & Threats",b14:"Protection & Defenses",
  b15:"Operations, Scripting & AI",b16:"Practice Exams & Exam Strategy",
  /* Topics */
  t1:"Power Supply Units (PSU) — form factors, modular vs fixed",
  t2:"Wattage Rating — calculating power requirements",
  t3:"Power Supply Connectors — 24-pin, 8-pin CPU, PCIe, SATA, Molex",
  t4:"Fan Cooling Systems — case fans, CPU coolers, airflow direction",
  t5:"Liquid Cooling Systems — AIO vs custom loop, radiators, pumps",
  t6:"Storage Devices — types overview, interfaces (SATA, NVMe, M.2)",
  t7:"Solid State Drives (SSDs) — NAND types, form factors, wear leveling",
  t8:"Hard Disk Drives (HDDs) — platters, RPM, cache, seek time",
  t9:"RAID — levels 0, 1, 5, 6, 10 — striping, mirroring, parity",
  t10:"Optical Drives — CD, DVD, Blu-ray, read/write speeds",
  t11:"System RAM — DDR4, DDR5, DIMM vs SO-DIMM, speeds & latency",
  t12:"ECC RAM — error-correcting code, server vs workstation use",
  t13:"CPU Architecture — x86 vs ARM, cores, threads, cache levels",
  t14:"CPU Sockets — Intel (LGA) vs AMD (PGA/LGA), compatibility",
  t15:"BIOS/UEFI — POST, boot order, Secure Boot, firmware updates",
  t16:"TPM (Trusted Platform Module) — hardware security, key storage",
  t17:"Troubleshoot POST — beep codes, diagnostic LEDs, no-display fixes",
  t18:"Power Issues — no power, intermittent shutdown, PSU testing",
  t19:"RAID Failure — degraded arrays, rebuild procedures, hot spares",
  t20:"Overheating — thermal paste, heatsink mounting, throttling signs",
  t21:"Switches — managed vs unmanaged, VLANs, PoE",
  t22:"UTP Cabling — Cat 5e/6/6a, T568A/B, crimping, cable testing",
  t23:"Modems — DSL, Cable, Fiber ONT, gateway devices",
  t24:"IPv4 Addressing — classes, subnetting, CIDR, private ranges",
  t25:"IPv6 Addressing — notation, link-local, global unicast, SLAAC",
  t26:"DHCP — leases, scopes, reservations, relay agents",
  t27:"DNS — records (A, AAAA, MX, CNAME, PTR), resolution process",
  t28:"File/Print Servers — SMB/CIFS, NFS, shared permissions",
  t29:"Proxy Servers — forward vs reverse proxy, content filtering",
  t30:"IoT Devices — smart devices, Zigbee, Z-Wave, security concerns",
  t31:"Hypervisors — Type 1 vs Type 2, VM snapshots, resource allocation",
  t32:"Cloud Characteristics — IaaS, PaaS, SaaS, public/private/hybrid",
  t33:"Mobile Hotspots — tethering, data limits, security",
  t34:"Battery Replacement — Li-ion safety, calibration, swelling risks",
  t35:"Laser Printer Process — 7 steps: Processing through Cleaning",
  t36:"Print Quality Issues — ghosting, streaks, smearing, paper jams",
  t37:"Windows / macOS — edition comparison, feature differences",
  t38:"Windows File Systems — NTFS, FAT32, exFAT, permissions model",
  t39:"Control Panel — applets, system settings, legacy vs Settings app",
  t40:"Administrative Tools — MMC snap-ins, Computer Management, Services",
  t41:"Disk Management — partitions (MBR vs GPT), volumes, format types",
  t42:"Command Prompt — dir, cd, ipconfig, sfc, chkdsk, DISM, net commands",
  t43:"Event Viewer — log types (System, Application, Security), filtering",
  t44:"Task Manager — processes, performance, startup, services tabs",
  t45:"System Restore — restore points, snapshot behavior, limitations",
  t46:"Linux Navigation — ls, cd, pwd, grep, chmod, sudo, package managers",
  t47:"Time Machine (macOS) — backup config, restore procedures, APFS snapshots",
  t48:"Logical Security — user accounts, groups, NTFS vs share permissions",
  t49:"Password Best Practices — complexity, length, MFA, password managers",
  t50:"Social Engineering — phishing, vishing, tailgating, pretexting",
  t51:"Malware Vectors — email, USB, drive-by downloads, supply chain",
  t52:"Defender Antivirus — real-time protection, scans, exclusions",
  t53:"BitLocker — full-disk encryption, TPM requirement, recovery keys",
  t54:"Backups — full, incremental, differential, 3-2-1 rule",
  t55:"Change Requests — documentation, rollback plans, approval process",
  t56:"Shell Scripts — batch files, PowerShell, bash basics, automation",
  t57:"AI Application Integration — copilots, prompt engineering basics",
  t58:"Private vs Public AI — data privacy, model hosting, enterprise concerns",
  t59:"Core 1 Exam Details — domain weights, question types, PBQ strategy",
  t60:"Core 2 Exam Details — domain weights, passing score differences",
  t61:"Exam Tips — time management, PBQ skip strategy, elimination method",
  t62:"Full timed practice exam — simulate test day conditions",
  /* Tips */
  tip1:"The 7 laser printer steps are GUARANTEED on the exam. Memorize the order.",
  tip2:"Know RAID levels cold: 0 = speed no redundancy, 1 = mirror, 5 = parity (min 3), 10 = mirror + stripe.",
  tip3:"DDR generations don't mix — DDR4 won't fit DDR5 slots. Know notch positions and voltage differences.",
  tip4:"1 short beep = POST success, continuous/repeating beeps usually mean memory issues.",
  tip5:"Troubleshoot order: wall outlet → power cable → PSU switch → PSU test → motherboard.",
  tip6:"T568B is the standard for straight-through. Know both A and B pinouts.",
  tip7:"Private IPs: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16. APIPA: 169.254.x.x = DHCP failure.",
  tip8:"Cloud characteristics: IaaS, PaaS, SaaS, public/private/hybrid.",
  tip9:"NTFS supports permissions, EFS encryption, compression, large files. FAT32 has 4GB file limit.",
  tip10:"sfc /scannow fixes system files, DISM repairs the image, chkdsk fixes disk errors. Order matters.",
  tip11:"Event Viewer levels: Information → Warning → Error → Critical. Security logs need auditing enabled.",
  tip12:"Linux permissions: rwx=7, rw-=6, r-x=5, r--=4. chmod 755 = owner full, group/others read+execute.",
  tip13:"MFA factors: something you know/have/are. Two of the SAME type is NOT MFA.",
  tip14:"BitLocker requires TPM 1.2+. Without TPM, you need a USB startup key.",
  tip15:"3-2-1 backup: 3 copies, 2 media types, 1 offsite. Know incremental vs differential.",
  tip16:"Core 1 = 675/900 (≈75%). Core 2 = 700/900 (≈78%). Skip PBQs first pass.",
  /* Guides */
  g1:"Module 3.1",g2:"Module 3.2",g3:"Module 3.3-3.4",g4:"Module 4.1",g5:"Module 4.2-4.3",
  g6:"Module 5.2-6.1",g7:"Module 6.2-6.4",g8:"Module 7.1-10.3",g9:"Module 11.3",g10:"Module 12.1-13.2",
  g11:"Module 14.3-14.4",g12:"Module 17.1-17.3",g13:"Module 15.1-19.4",g14:"Module 19.2",g15:"Module 21.1-21.3",g16:"Appendix B-C",
  /* Time slots */
  morning:"MORNING",midday:"MIDDAY",afternoon:"AFTERNOON",evening:"EVENING",lateEvening:"LATE EVENING",
  time1:"9:00 AM – 11:00 AM",time2:"11:30 AM – 1:30 PM",time3:"2:30 PM – 4:30 PM",time4:"5:00 PM – 7:00 PM",time5:"7:30 PM – 9:00 PM",
  attribution:"Study content structured from TestOut LabSim A+ courseware modules. CompTIA A+ is a trademark of CompTIA.",
},
es:{
  _name:"Español",_code:"es",
  sprint:"SPRINT DE 4 DÍAS",title:"Mapa de Estudio A+",
  subtitle1:"Core 1 (220-1101): 675/900 · 90 preguntas · 90 min",
  subtitle2:"Core 2 (220-1102): 700/900 · 90 preguntas · 90 min",
  topicsCovered:"temas cubiertos",
  studyMap:"Mapa de Estudio",ports:"Puertos",acronyms:"Acrónimos",
  tapToReveal:"Toca la tarjeta para revelar",whatService:"¿Qué servicio / puerto?",
  whatStandFor:"¿Qué significa?",prev:"← Anterior",next:"Siguiente →",
  quickRef:"Referencia Rápida",resetAll:"Reiniciar Todo",
  resetConfirm:"¿Reiniciar todo el progreso? No se puede deshacer.",
  confidence:"Confianza:",
  conf1:"🔴 Aún no",conf2:"🟡 Inestable",conf3:"🟢 Sólido",conf4:"💎 Dominado",
  openLab:"Abrir en TestOut",
  core1:"CORE 1",core2:"CORE 2",
  day1:"HARDWARE Y ENERGÍA",day1sub:"Core 1 — Fuentes, Almacenamiento, Memoria, CPUs, Arranque y Fallos",
  day2:"REDES Y NUBE",day2sub:"Core 1 — Cableado, IP, Servicios, Nube, Móvil, Impresoras",
  day3:"SISTEMAS OPERATIVOS",day3sub:"Core 2 — Windows, Linux, macOS, Herramientas y Soporte",
  day4:"SEGURIDAD Y OPERACIONES",day4sub:"Core 2 — Amenazas, Protección, Operaciones, IA y Exámenes",
  day1short:"HARDWARE",day2short:"REDES",day3short:"SO",day4short:"SEGURIDAD",
  attribution:"Contenido estructurado a partir de los módulos de TestOut LabSim A+. CompTIA A+ es marca registrada de CompTIA.",
}
};
